export default {
    state: {
        lab_main_list: [],
        lab_firs_name_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
        lab_name_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
        lab_norma_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
        lab_edzm_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
        lab_center_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
        lab_result_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
        lab_second_name_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
        lab_first_result_list: [
            {
                name_1: '',
                name_2: '',
                name_3: '',
                name_4: '',
                name_5: '',
                name_6: '',
                name_7: '',
                name_8: '',
                name_9: '',
                name_10: '',
                name_11: '',
                name_12: '',
                name_13: '',
                name_14: '',
                name_15: '',
                name_16: '',
                name_17: '',
                name_18: '',
                name_19: '',
                name_20: '',
                name_21: '',
                name_22: '',
                name_23: '',
                name_24: '',
                name_25: '',
                name_26: '',
                name_27: '',
                name_28: '',
                name_29: '',
                name_30: '',
                name_31: '',
                name_32: '',
                name_33: '',
                name_34: '',
                name_35: '',
                name_36: '',
                name_37: '',
                name_38: '',
                name_39: '',
                name_40: '',
                name_41: '',
                name_42: '',
                name_43: '',
                name_44: '',
                name_45: '',
                name_46: '',
                name_47: '',
                name_48: '',
                name_49: '',
                name_50: '',
            }
        ],
    },
    actions: {
        async fetch_lab_main_list(ctx) {
            
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicmains');
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Updatelab_main_list', res_data);
        },
        async fetch_lab_firs_name_list(ctx, id) {
            ctx.lab_firs_name_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicFirstNames/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_firs_name_list', res_data);
        },
        async fetch_lab_name_list(ctx, id) {
            ctx.lab_name_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicLabTitles/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_name_list', res_data);
        },
        async fetch_lab_norma_list(ctx, id) {
            ctx.lab_norma_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicNormas/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_norma_list', res_data);
        },
        
        async fetch_lab_edzm_list(ctx, id) {
            ctx.lab_edzm_lis = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicUnitMeasurments/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_edzm_list', res_data);
        },
        async fetch_lab_center_list(ctx, id) {
            ctx.lab_center_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicCenterNames/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_center_list', res_data);
        },
        async fetch_lab_result_list(ctx, id) {
            ctx.lab_result_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicNameTitles/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_result_list', res_data);
        },
        async fetch_lab_second_name_list(ctx, id) {
            ctx.lab_second_name_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicFirstNameSeconds/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_second_name_list', res_data);
        },
        async fetch_lab_first_result_list(ctx, id) {
            ctx.lab_first_result_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
            ];
            const res = await fetch(ctx.rootState.hostname + '/HospitalAnalizDynamicResultFirst/getPaginationByMainTableId?page=0&size=1&main_table_id=' + id);
            const res_data = await res.json();
            // console.log(ctx.rootState.hostname);
            ctx.commit('Update_lab_first_result_list', res_data);
        },
        
    },
    mutations: {
        Updatelab_main_list(state, data) {
            state.lab_main_list = data;
        },
        Update_lab_firs_name_list(state, data) {
            if(data.items_list.length>0){
                state.lab_firs_name_list = data.items_list;
            }
            else{
               state.lab_firs_name_list = [
                {
                    name_1: '',
                    name_2: '',
                    name_3: '',
                    name_4: '',
                    name_5: '',
                    name_6: '',
                    name_7: '',
                    name_8: '',
                    name_9: '',
                    name_10: '',
                    name_11: '',
                    name_12: '',
                    name_13: '',
                    name_14: '',
                    name_15: '',
                    name_16: '',
                    name_17: '',
                    name_18: '',
                    name_19: '',
                    name_20: '',
                    name_21: '',
                    name_22: '',
                    name_23: '',
                    name_24: '',
                    name_25: '',
                    name_26: '',
                    name_27: '',
                    name_28: '',
                    name_29: '',
                    name_30: '',
                    name_31: '',
                    name_32: '',
                    name_33: '',
                    name_34: '',
                    name_35: '',
                    name_36: '',
                    name_37: '',
                    name_38: '',
                    name_39: '',
                    name_40: '',
                    name_41: '',
                    name_42: '',
                    name_43: '',
                    name_44: '',
                    name_45: '',
                    name_46: '',
                    name_47: '',
                    name_48: '',
                    name_49: '',
                    name_50: '',
                }
               ] 
            }
        },
        Update_lab_name_list(state, data) {
            if(data.items_list.length>0){
                state.lab_name_list = data.items_list;
            }
        },
        Update_lab_norma_list(state, data) {
            if(data.items_list.length>0){
                state.lab_norma_list = data.items_list;
            }
        },
        Update_lab_edzm_list(state, data) {
            if(data.items_list.length>0){
                state.lab_edzm_list = data.items_list;
            }
            else{
                state.lab_edzm_list = [
                 {
                     name_1: '',
                     name_2: '',
                     name_3: '',
                     name_4: '',
                     name_5: '',
                     name_6: '',
                     name_7: '',
                     name_8: '',
                     name_9: '',
                     name_10: '',
                     name_11: '',
                     name_12: '',
                     name_13: '',
                     name_14: '',
                     name_15: '',
                     name_16: '',
                     name_17: '',
                     name_18: '',
                     name_19: '',
                     name_20: '',
                     name_21: '',
                     name_22: '',
                     name_23: '',
                     name_24: '',
                     name_25: '',
                     name_26: '',
                     name_27: '',
                     name_28: '',
                     name_29: '',
                     name_30: '',
                     name_31: '',
                     name_32: '',
                     name_33: '',
                     name_34: '',
                     name_35: '',
                     name_36: '',
                     name_37: '',
                     name_38: '',
                     name_39: '',
                     name_40: '',
                     name_41: '',
                     name_42: '',
                     name_43: '',
                     name_44: '',
                     name_45: '',
                     name_46: '',
                     name_47: '',
                     name_48: '',
                     name_49: '',
                     name_50: '',
                 }
                ] 
             }
        },
        Update_lab_center_list(state, data) {
            if(data.items_list.length>0){
                state.lab_center_list = data.items_list;
            }
            else{
                state.lab_center_list = [
                 {
                     name_1: '',
                     name_2: '',
                     name_3: '',
                     name_4: '',
                     name_5: '',
                     name_6: '',
                     name_7: '',
                     name_8: '',
                     name_9: '',
                     name_10: '',
                     name_11: '',
                     name_12: '',
                     name_13: '',
                     name_14: '',
                     name_15: '',
                     name_16: '',
                     name_17: '',
                     name_18: '',
                     name_19: '',
                     name_20: '',
                     name_21: '',
                     name_22: '',
                     name_23: '',
                     name_24: '',
                     name_25: '',
                     name_26: '',
                     name_27: '',
                     name_28: '',
                     name_29: '',
                     name_30: '',
                     name_31: '',
                     name_32: '',
                     name_33: '',
                     name_34: '',
                     name_35: '',
                     name_36: '',
                     name_37: '',
                     name_38: '',
                     name_39: '',
                     name_40: '',
                     name_41: '',
                     name_42: '',
                     name_43: '',
                     name_44: '',
                     name_45: '',
                     name_46: '',
                     name_47: '',
                     name_48: '',
                     name_49: '',
                     name_50: '',
                 }
                ] 
             }
        },
        Update_lab_result_list(state,data){
            if(data.items_list.length>0){
                state.lab_result_list = data.items_list;
            }
            else{
                state.lab_result_list = [
                 {
                     name_1: '',
                     name_2: '',
                     name_3: '',
                     name_4: '',
                     name_5: '',
                     name_6: '',
                     name_7: '',
                     name_8: '',
                     name_9: '',
                     name_10: '',
                     name_11: '',
                     name_12: '',
                     name_13: '',
                     name_14: '',
                     name_15: '',
                     name_16: '',
                     name_17: '',
                     name_18: '',
                     name_19: '',
                     name_20: '',
                     name_21: '',
                     name_22: '',
                     name_23: '',
                     name_24: '',
                     name_25: '',
                     name_26: '',
                     name_27: '',
                     name_28: '',
                     name_29: '',
                     name_30: '',
                     name_31: '',
                     name_32: '',
                     name_33: '',
                     name_34: '',
                     name_35: '',
                     name_36: '',
                     name_37: '',
                     name_38: '',
                     name_39: '',
                     name_40: '',
                     name_41: '',
                     name_42: '',
                     name_43: '',
                     name_44: '',
                     name_45: '',
                     name_46: '',
                     name_47: '',
                     name_48: '',
                     name_49: '',
                     name_50: '',
                 }
                ] 
            }
        },
        Update_lab_second_name_list(state,data){
            if(data.items_list.length>0){
                state.lab_second_name_list = data.items_list;
            }
            else{
                state.lab_second_name_list = [
                 {
                     name_1: '',
                     name_2: '',
                     name_3: '',
                     name_4: '',
                     name_5: '',
                     name_6: '',
                     name_7: '',
                     name_8: '',
                     name_9: '',
                     name_10: '',
                     name_11: '',
                     name_12: '',
                     name_13: '',
                     name_14: '',
                     name_15: '',
                     name_16: '',
                     name_17: '',
                     name_18: '',
                     name_19: '',
                     name_20: '',
                     name_21: '',
                     name_22: '',
                     name_23: '',
                     name_24: '',
                     name_25: '',
                     name_26: '',
                     name_27: '',
                     name_28: '',
                     name_29: '',
                     name_30: '',
                     name_31: '',
                     name_32: '',
                     name_33: '',
                     name_34: '',
                     name_35: '',
                     name_36: '',
                     name_37: '',
                     name_38: '',
                     name_39: '',
                     name_40: '',
                     name_41: '',
                     name_42: '',
                     name_43: '',
                     name_44: '',
                     name_45: '',
                     name_46: '',
                     name_47: '',
                     name_48: '',
                     name_49: '',
                     name_50: '',
                 }
                ] 
            }
        },
        Update_lab_first_result_list(state,data){
            if(data.items_list.length>0){
                state.lab_first_result_list = data.items_list;
            }
            else{
                state.lab_first_result_list = [
                 {
                     name_1: '',
                     name_2: '',
                     name_3: '',
                     name_4: '',
                     name_5: '',
                     name_6: '',
                     name_7: '',
                     name_8: '',
                     name_9: '',
                     name_10: '',
                     name_11: '',
                     name_12: '',
                     name_13: '',
                     name_14: '',
                     name_15: '',
                     name_16: '',
                     name_17: '',
                     name_18: '',
                     name_19: '',
                     name_20: '',
                     name_21: '',
                     name_22: '',
                     name_23: '',
                     name_24: '',
                     name_25: '',
                     name_26: '',
                     name_27: '',
                     name_28: '',
                     name_29: '',
                     name_30: '',
                     name_31: '',
                     name_32: '',
                     name_33: '',
                     name_34: '',
                     name_35: '',
                     name_36: '',
                     name_37: '',
                     name_38: '',
                     name_39: '',
                     name_40: '',
                     name_41: '',
                     name_42: '',
                     name_43: '',
                     name_44: '',
                     name_45: '',
                     name_46: '',
                     name_47: '',
                     name_48: '',
                     name_49: '',
                     name_50: '',
                 }
                ] 
            }
        },

    },
    getters: {
        get_lab_main_list(state) {
            return state.lab_main_list;
        },
        get_lab_firs_name_list(state) {
            return state.lab_firs_name_list;
        },
        get_lab_name_list(state) {
            return state.lab_name_list;
        },
        get_lab_norma_list(state) {
            return state.lab_norma_list;
        },
        get_lab_edzm_list(state) {
            return state.lab_edzm_list;
        },
        get_lab_center_list(state) {
            return state.lab_center_list;
        },
        get_lab_result_list(state) {
            return state.lab_result_list;
        },
        get_lab_second_name_list(state) {
            return state.lab_second_name_list;
        },
        get_lab_first_result_list(state) {
            return state.lab_first_result_list;
        },
    }
}