{ "title": "qon_garmon", "icon": "atom", "url": "/qon_garmon", "view": false, "color": "#800080" },
{ "title": "GarmonlarQon", "icon": "ambulance", "url": "/garmonlarQon", "view": false, "color":"#4682B4" },
{ "title": "Remaproba", "icon": "ambulance", "url": "/remaproba", "view": false, "color":"#4682B4" },
{ "title": "Koagulogramma", "icon": "atom", "url": "/kalogramma", "view": false, "color": "#800080" },
{ "title": "Umumiy_qon", "icon": "ambulance", "url":" /umum_qon2", "view": false, "color":"#4682B4"},
{ "title": "BioximyaKrov", "icon": "ambulance", "url": "/biox_krov", "view": false, "color":"#4682B4"},
{ "title": "Mazok_step", "icon": "ambulance", "url":" /mazok_step", "view": false, "color":"#4682B4"},
{ "title": "vsk_sux", "icon": "ambulance", "url": "/vsk_sux", "view": false, "color":"#4682B4"},
{ "title": "krov_kolvo", "icon": "ambulance", "url": "/krov_kolvo", "view": false, "color":"#4682B4" },
{ "title": "lipid_spek", "icon": "ambulance", "url": "/lipid_spek", "view": false, "color":"#4682B4" },
{ "title": "glik_gemok", "icon": "ambulance", "url": "/glik_gemok", "view": false, "color":"#4682B4" },
{ "title": "Peshob1", "icon": "ambulance", "url": "/obshey_mochi", "view": false, "color":"#4682B4" },
{ "title": "mazok_10", "icon": "ambulance", "url": "/mazok_10", "view": false, "color":"#4682B4" },
{ "title": "gruppa_krov", "icon": "ambulance", "url": "/gruppa_kolvo", "view": false, "color":"#4682B4" },
{ "title": "Nechiporenko", "icon": "ambulance", "url": "/nechiporenko", "view": false, "color":"#4682B4" },

{ "title": "CovidExpress", "icon": "clinic-medical", "url": "/covidExpress", "view": false, "color": "#FF7F50" },
{ "title": "CovidQon", "icon": "hospital-alt", "url": "/covidQon", "view": false, "color": "#4B0082" },
{ "title": "ExpressGepatitBC", "icon":" biohazard", "url": "/ExpressBC", "view": false, "color": "#00FF00" },
{ "title": "GepatitBC", "icon": "diagnoses", "url": "/gepatitBC", "view": false, "color":"#FFA500" },
{ "title": "Koagulogramma", "icon": "atom", "url": "/koagulogramma", "view": false, "color": "#800080" },
{ "title": "Mazok", "icon": "ambulance", "url": "/mazok", "view": false, "color":"#4682B4" },
{ "title": "Onkomarker", "icon": "ambulance", "url": "/onkomarker", "view": false, "color":"#4682B4" },
{ "title": "Rv", "icon": "ambulance", "url": "/rv", "view": false, "color":"#4682B4" },
{ "title": "Spid", "icon": "ambulance", "url": "/spid", "view": false, "color":"#4682B4" },
{ "title": "Torch", "icon": "ambulance", "url": "/torch", "view": false, "color":"#4682B4" },

{ "title": "spirmagromma", "icon": "ambulance", "url": "/spirma", "view": false, "color":"#4682B4" },
{ "title": "Vsk", "icon": "ambulance", "url": /vsk, "view": false, "color":"#4682B4" },
{ "title": "opuxoloviya", "icon": "ambulance", "url": "/opuxoloviya", "view": false, "color":"#4682B4" },
{ "title": "Peshob", "icon": "ambulance", "url": "/peshob", "view": false, "color":"#4682B4" }
// { "title": "bioximechisky", "icon": "ambulance", "url": "/bioximechisky", "view": false, "color":"#4682B4" },
// { "title": bioximechisky, "icon": "user", "url": "/biox", "view": true, "color": "#191970" },
// { "title": "Umumiy_qon", "icon": "atom", "url": "/obshey_krov", "view": false, "color": "#800080" },
// { "title": Работника, "icon": user-md, "url": /users, "view": true, "color": "#20B2AA" },
  //   { "title": "Umumiy_qon1", "icon": "ambulance", "url": /um_qon, "view": false, "color":"#4682B4" },
// { "title": bioximechisky, "icon": "user", "url": "/biox", "view": true, "color": "#191970" },